# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 493)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.copy_t1tot2 = QtWidgets.QPushButton(self.centralwidget)
        self.copy_t1tot2.setGeometry(QtCore.QRect(270, 136, 99, 61))
        self.copy_t1tot2.setStyleSheet("background-color: rgb(124, 122, 203);")
        self.copy_t1tot2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imagenes/585e47b5cb11b227491c338b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_t1tot2.setIcon(icon)
        self.copy_t1tot2.setIconSize(QtCore.QSize(30, 30))
        self.copy_t1tot2.setObjectName("copy_t1tot2")
        self.copy_t2tot1 = QtWidgets.QPushButton(self.centralwidget)
        self.copy_t2tot1.setGeometry(QtCore.QRect(270, 220, 99, 61))
        self.copy_t2tot1.setStyleSheet("background-color: rgb(124, 122, 203);\n"
"")
        self.copy_t2tot1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Imagenes/585e47b5cb11b227491c338b (copia).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_t2tot1.setIcon(icon1)
        self.copy_t2tot1.setIconSize(QtCore.QSize(30, 30))
        self.copy_t2tot1.setObjectName("copy_t2tot1")
        self.cd_tree1 = QtWidgets.QPushButton(self.centralwidget)
        self.cd_tree1.setGeometry(QtCore.QRect(20, 380, 71, 61))
        self.cd_tree1.setStyleSheet("background-color: rgb(52, 218, 63);")
        self.cd_tree1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Imagenes/-create-new-folder_90671.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cd_tree1.setIcon(icon2)
        self.cd_tree1.setIconSize(QtCore.QSize(60, 60))
        self.cd_tree1.setObjectName("cd_tree1")
        self.cf_tree1 = QtWidgets.QPushButton(self.centralwidget)
        self.cf_tree1.setGeometry(QtCore.QRect(100, 380, 71, 61))
        self.cf_tree1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cf_tree1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Imagenes/WhatsApp Image 2019-08-13 at 11.53.46 PM.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cf_tree1.setIcon(icon3)
        self.cf_tree1.setIconSize(QtCore.QSize(60, 60))
        self.cf_tree1.setObjectName("cf_tree1")
        self.delete_tree1 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_tree1.setGeometry(QtCore.QRect(180, 380, 71, 61))
        self.delete_tree1.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.delete_tree1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Imagenes/121113.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_tree1.setIcon(icon4)
        self.delete_tree1.setIconSize(QtCore.QSize(50, 50))
        self.delete_tree1.setObjectName("delete_tree1")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(220, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(0, 0, 0);")
        self.title.setObjectName("title")
        self.cf_tree2 = QtWidgets.QPushButton(self.centralwidget)
        self.cf_tree2.setGeometry(QtCore.QRect(470, 380, 71, 61))
        self.cf_tree2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cf_tree2.setText("")
        self.cf_tree2.setIcon(icon3)
        self.cf_tree2.setIconSize(QtCore.QSize(60, 60))
        self.cf_tree2.setObjectName("cf_tree2")
        self.cd_tree2 = QtWidgets.QPushButton(self.centralwidget)
        self.cd_tree2.setGeometry(QtCore.QRect(390, 380, 71, 61))
        self.cd_tree2.setStyleSheet("background-color: rgb(52, 218, 63);")
        self.cd_tree2.setText("")
        self.cd_tree2.setIcon(icon2)
        self.cd_tree2.setIconSize(QtCore.QSize(60, 60))
        self.cd_tree2.setObjectName("cd_tree2")
        self.delete_tree2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_tree2.setGeometry(QtCore.QRect(550, 380, 71, 61))
        self.delete_tree2.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.delete_tree2.setText("")
        self.delete_tree2.setIcon(icon4)
        self.delete_tree2.setIconSize(QtCore.QSize(50, 50))
        self.delete_tree2.setObjectName("delete_tree2")
        self.lwTree1 = QtWidgets.QListWidget(self.centralwidget)
        self.lwTree1.setGeometry(QtCore.QRect(20, 70, 231, 291))
        self.lwTree1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lwTree1.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lwTree1.setObjectName("lwTree1")
        self.lwTree2 = QtWidgets.QListWidget(self.centralwidget)
        self.lwTree2.setGeometry(QtCore.QRect(390, 70, 231, 291))
        self.lwTree2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lwTree2.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lwTree2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.lwTree2.setObjectName("lwTree2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Proyect"))
        self.title.setText(_translate("MainWindow", "File System"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

